local Gps = {
		GpsNormal = {fg = C.gray, bg = "#1d1d1d", },
		GpsItemKindFunction = {fg = C.ui_purple, },
		GpsItemKindMethod = {fg = C.ui_purple, },
		GpsItemKindConstructor = {fg = C.ui_orange, },
		GpsItemKindClass = {fg = C.ui_orange, },
		GpsItemKindEnum = {fg = C.ui_orange, },
		GpsItemKindEvent = {fg = C.ui_purple, },
		GpsItemKindInterface = {fg = C.light_blue, },
		GpsItemKindStruct = {fg = C.ui4_blue, },
		GpsItemKindVariable = {fg = C.ui4_blue, },
		GpsItemKindField = {fg = C.ui4_blue, },
		GpsItemKindProperty = {fg = C.ui4_blue, },
		GpsItemKindEnumMember = {fg = C.light_blue, },
		GpsItemKindConstant = {fg = C.ui4_blue, },
		GpsItemKindKeyword = {fg = C.fg, },
		GpsItemKindModule = {fg = C.fg, },
		GpsItemKindValue = {fg = C.fg, },
		GpsItemKindUnit = {fg = C.fg, },
		GpsItemKindText = {fg = C.fg, },
		GpsItemKindSnippet = {fg = C.fg, },
		GpsItemKindFile = {fg = C.fg, },
		GpsItemKindFolder = {fg = C.fg, },
		GpsItemKindColor = {fg = C.fg, },
		GpsItemKindReference = {fg = C.fg, },
		GpsItemKindOperator = {fg = C.fg, },
		GpsItemKindTypeParameter = {fg = C.fg, },
}

return Gps