local NvimTree = {
		NvimTreeFolderIcon = {fg = C.folder, },
		NvimTreeIndentMarker = {fg = "#c5c5c5", },
		NvimTreeNormal = {fg = C.light_gray, bg = C.tree_gray, },
		NvimTreeVertSplit = {fg = C.alt_bg, bg = C.alt_bg, },
		NvimTreeFolderName = {fg = C.folder, },
		NvimTreeOpenedFolderName = {fg = C.folder, style = "bold,italic", },
		NvimTreeEmptyFolderName = {fg = C.gray, style = "italic", },
		NvimTreeGitIgnored = {fg = C.gray, style = "italic", },
		NvimTreeImageFile = {fg = C.light_gray, },
		NvimTreeSpecialFile = {fg = C.orange, },
		NvimTreeEndOfBuffer = {fg = C.tree_gray, },
		NvimTreeCursorLine = {bg = "#282b37", },
		NvimTreeGitignoreIcon = {fg = "#E64A19", },
		NvimTreeGitStaged = {fg = C.tree_sign_add, },
		NvimTreeGitNew = {fg = C.tree_sign_add, },
		NvimTreeGitRenamed = {fg = C.tree_sign_add, },
		NvimTreeGitDeleted = {fg = C.sign_delete, },
		NvimTreeGitMerge = {fg = C.tree_sign_change, },
		NvimTreeGitDirty = {fg = C.tree_sign_change, },
		NvimTreeSymlink = {fg = C.cyan, },
		NvimTreeRootFolder = {fg = C.fg, style = "bold", },
		NvimTreeExecFile = {fg = "#9FBA89", },
}

return NvimTree